### ISSUE TITLE
메인 화면2

### ISSUE THREAD

**Issue by minhuits** [minhuits/one_hand_planner#2]
## 디자인
![Frame 124](https://user-images.githubusercontent.com/58944350/167303614-83523726-6996-45a9-bdf9-3d5a8f7c1a92.png)

## ToDo List
- [ ] 계획 screen : TODO 탭
- [ ] 기록 screen : 일기장 탭
- [ ] 기록 screen : 메모 탭
- [ ] 설정 screen
